# clinical Care Guidance for MedIQ AI
# This file contains safe, non-prescriptive care suggestions and OTC info in a conversational paragraph format.

DISEASE_GUIDANCE = {
    "Fungal infection": "Keep the affected area clean and dry to prevent further irritation. Cotton clothing is recommended. Topical antifungal creams are commonly used for relief, but any medication should be confirmed with a healthcare professional.",
    "Allergy": "Avoiding known allergens is the best way to prevent symptoms. Over-the-counter antihistamines are often used for temporary relief of itching or sneezing. If breathing is affected, seek immediate medical attention.",
    "GERD": "Eating smaller meals and avoiding lying down immediately after eating can help manage symptoms. Over-the-counter antacids or acid reducers may provide temporary relief. Consult a doctor for long-term management.",
    "Chronic cholestasis": "Management focuses on supporting liver health and reducing itching. Maintaining hydration and a balanced diet is important. Treatment requires careful supervision by a liver specialist.",
    "Drug Reaction": "Immediately stop taking the suspected medication and consult a doctor. Cold compresses or over-the-counter antihistamines may help with skin itching, but professional evaluation is essential to rule out severe reactions.",
    "Peptic ulcer diseae": "Avoiding spicy foods, alcohol, and caffeine can help reduce stomach irritation. Over-the-counter acid blockers are sometimes used to manage discomfort, but persistent pain requires professional medical evaluation.",
    "AIDS": "Management involves specialized medical care and antiretroviral therapy. Support groups and healthy lifestyle choices are also beneficial. Regular follow-ups with a healthcare team are essential.",
    "Diabetes ": "Managing blood sugar levels through diet, exercise, and prescribed treatment is key. Regular monitoring and foot care are also important. Diabetes requires lifelong medical supervision.",
    "Gastroenteritis": "The primary goal is to stay hydrated using water or oral rehydration solutions. Small, bland meals like rice or toast may be easier to tolerate. Seek care if you cannot keep fluids down.",
    "Bronchial Asthma": "Avoid triggers like smoke, dust, or pets. Maintaining a clean environment and using prescribed inhalers as directed by a doctor is essential. Seek emergency care for severe breathing difficulty.",
    "Hypertension ": "Reducing salt intake and maintaining a healthy weight through regular exercise can help lower blood pressure. Regular monitoring and professional medical supervision are required for long-term health.",
    "Migraine": "Resting in a quiet, dark room can help during an attack. Hydration and maintaining a regular sleep schedule may prevent future episodes. Over-the-counter pain relievers are commonly used for relief.",
    "Cervical spondylosis": "Gentle neck exercises and maintaining good posture can reduce discomfort. Applying heat or ice to the area may provide relief. Consult a physical therapist for specialized guidance.",
    "Paralysis (brain hemorrhage)": "This is a critical medical emergency. Immediate hospital intervention is required. Do not attempt home treatment. Rehabilitation and long-term care will be managed by a medical team.",
    "Jaundice": "Rest and avoiding alcohol are crucial to support liver recovery. Hydration and a low-fat diet may be recommended. Jaundice is a sign of an underlying issue that requires professional medical diagnosis.",
    "Malaria": "Treatment requires specific prescription medications administered by a healthcare professional. Bed rest and hydration are important during recovery. Seek care immediately if fever and chills persist.",
    "Chicken pox": "Focus on relieving itching with cool baths or soothing lotions. Avoid scratching to prevent infection. Over-the-counter fever reducers like paracetamol can be used, but avoid aspirin in children.",
    "Dengue": "Stay well-hydrated and rest as much as possible. Over-the-counter pain relievers like paracetamol are commonly used, but avoid NSAIDs (like ibuprofen or aspirin) as they can increase bleeding risk. Professional monitoring is essential.",
    "Typhoid": "Treatment requires professional medical diagnosis and a full course of prescribed antibiotics. Maintaining hydration and eating easily digestible foods can support recovery.",
    "hepatitis A": "Management is primarily supportive, focuses on rest and hydration. Avoiding alcohol and certain medications to protect the liver is essential. Recovery usually occurs within a few weeks.",
    "Hepatitis B": "Long-term management depends on the activity of the virus. Regular blood tests and liver monitoring under medical supervision are required. A healthy lifestyle helps protect the liver.",
    "Hepatitis C": "Modern treatments can effectively cure the infection, but require specific prescribed antiviral medications. Regular follow-ups with a specialist are necessary.",
    "Hepatitis D": "This is a serious condition that requires management by a liver specialist. Treatment is often specialized and involves regular monitoring of liver function.",
    "Hepatitis E": "Usually self-limiting, focusing on rest and hydration. Pregnant women and those with existing liver conditions should be closely monitored by a healthcare professional.",
    "Alcoholic hepatitis": "Complete cessation of alcohol is the most critical step for liver recovery. Nutritional support and professional medical management are essential.",
    "Tuberculosis": "Tuberculosis requires a strict, long-term course of prescribed antibiotics monitored by health professionals. Adhering to the full treatment plan is essential to prevent resistance.",
    "Common Cold": "Rest and staying hydrated are the most effective ways to manage symptoms. Over-the-counter decongestants or gargling with warm salt water may provide temporary comfort.",
    "Pneumonia": "Management includes rest, hydration, and often prescribed antibiotics or antivirals. Seek immediate medical attention if breathing becomes difficult or chest pain occurs.",
    "Dimorphic hemmorhoids(piles)": "Increasing fiber intake and staying hydrated can help soften stools and reduce strain. Over-the-counter topical ointments may provide temporary relief from itching.",
    "Heart attack": "This is a life-threatening emergency. Call local emergency services immediately. Do not attempt home treatment. Every minute is critical for cardiac recovery.",
    "Varicose veins": "Wearing compression stockings and elevating legs when resting can improve circulation. Regular movement and maintaining a healthy weight also help manage symptoms.",
    "Hypothyroidism": "Management involves thyroid hormone replacement therapy prescribed and monitored by a doctor. Regular blood tests ensure the correct dosage and long-term health.",
    "Hyperthyroidism": "Treatment focuses on reducing excess thyroid hormone production through prescribed medications or other therapies. Professional medical supervision is essential.",
    "Hypoglycemia": "Immediate intake of fast-acting glucose (like juice or honey) can raise blood sugar. Follow up with a balanced snack. If the user becomes unconscious, seek emergency medical care.",
    "Osteoarthristis": "Low-impact exercise like swimming can help maintain joint mobility. Weight management reduces stress on joints. Over-the-counter pain relievers are often used for symptoms.",
    "Arthritis": "Maintaining an active lifestyle and a healthy weight can improve joint function. Applying heat or cold to affected areas often provides relief. Consult a rheumatologist for specialized care.",
    "(vertigo) Paroymsal  Positional Vertigo": "Specific head movements (repositioning maneuvers) guided by a professional are often effective. Avoid sudden position changes and ensure your environment is safe from falls.",
    "Acne": "Gently washing the skin twice a day and using non-comedogenic products can help. Over-the-counter topical treatments are commonly used, but severe acne requires professional dermatological care.",
    "Urinary tract infection": "Drinking plenty of water can help flush out bacteria. Treatment typically requires a course of prescribed antibiotics. Seek medical care promptly to prevent kidney infection.",
    "Psoriasis": "Keeping the skin moisturized and using over-the-counter medicated creams can help manage plaques. Avoiding triggers and consulting a dermatologist for specialized treatment is recommended.",
    "Impetigo": "Keep the sores clean and covered to prevent the spread of bacteria. Treatment usually requires topical or oral antibiotics prescribed by a healthcare professional."
}
